CREATE TABLE IF NOT EXISTS bookings (
    id             CHAR(36)     NOT NULL PRIMARY KEY,
    user_id        CHAR(36)     NOT NULL,
    package_id     CHAR(36)     NOT NULL,
    visit_date     DATE         NOT NULL,
    quantity       INT          NOT NULL,
    unit_cents     BIGINT       NOT NULL,
    currency       VARCHAR(3)   NOT NULL DEFAULT 'IDR',
    status         VARCHAR(20)  NOT NULL DEFAULT 'pending_payment',
    payment_ref    VARCHAR(100) NULL,
    ticket_code    VARCHAR(20)  NULL,
    checked_in_at  DATETIME(3)  NULL,
    checked_in_by  CHAR(36)     NULL,
    created_at     DATETIME(3)  NOT NULL,
    updated_at     DATETIME(3)  NOT NULL,
    deleted_at     DATETIME(3)  NULL,
    UNIQUE KEY uq_bookings_ticket_code (ticket_code),
    KEY idx_bookings_user_id (user_id),
    KEY idx_bookings_package_visit_date (package_id, visit_date),
    KEY idx_bookings_status (status),
    KEY idx_bookings_payment_ref (payment_ref),
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_package FOREIGN KEY (package_id) REFERENCES tourism_packages(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
