export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  PACKAGES: "/packages",
  PACKAGE_DETAIL: (id: string) => `/packages/${id}`, // ID-based: backend package domain only supports FindByID (see package-card.tsx's comment)
  ARTICLES: "/articles",
  ARTICLE_DETAIL: (slug: string) => `/articles/${slug}`,
  GALLERY: "/gallery",

  ABOUT: "/about",
  FAQ: "/faq",
  CONTACT: "/contact",
  BOOKING: "/booking",
  PAYMENT: "/payment",
  E_TICKET: "/e-ticket",

  DASHBOARD: "/dashboard",
  DASHBOARD_BOOKING: "/dashboard/booking",
  DASHBOARD_PROFILE: "/dashboard/profile",

  ADMIN: "/admin/dashboard",
  ADMIN_TICKETS: "/admin/tickets",
  ADMIN_BOOKINGS: "/admin/bookings",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_VISITORS: "/admin/visitors",
  ADMIN_USERS: "/admin/users",
  ADMIN_CONTENT: "/admin/content",
  ADMIN_REPORTS: "/admin/reports",
  ADMIN_ARTICLES: "/admin/articles",
  ADMIN_GALLERY: "/admin/gallery",
  ADMIN_PACKAGES: "/admin/packages",

  MANAGER: "/manager/dashboard",
  MANAGER_SALES: "/manager/sales",
  MANAGER_REVENUE: "/manager/revenue",
  MANAGER_BOOKINGS: "/manager/bookings",
  MANAGER_VISITORS: "/manager/visitors",
  MANAGER_MONITORING: "/manager/monitoring",

  PETUGAS: "/petugas/dashboard",
  PETUGAS_SCAN: "/petugas/scan",
  PETUGAS_HISTORY: "/petugas/history",
  PETUGAS_TICKET: "/petugas/ticket",
} as const;
